export const SolvedAcTier = [
    "표시하지않음",
    "Master",
    "Ruby 1",
    "Ruby 2",
    "Ruby 3",
    "Ruby 4",
    "Ruby 5",
    "Diamond 1",
    "Diamond 2",
    "Diamond 3",
    "Diamond 4",
    "Diamond 5",
    "Platinum 1",
    "Platinum 2",
    "Platinum 3",
    "Platinum 4",
    "Platinum 5",
    "Gold 1",
    "Gold 2",
    "Gold 3",
    "Gold 4",
    "Gold 5",
    "Silver 1",
    "Silver 2",
    "Silver 3",
    "Silver 4",
    "Silver 5",
    "Bronze 1",
    "Bronze 2",
    "Bronze 3",
    "Bronze 4",
    "Bronze 5",
]

export const CodeforcesTier = [
    "표시하지않음",
    "Legendary Grandmaster",
    "Grandmaster",
    "Master",
    "Candidate Master",
    "Expert",
    "Specialist",
    "Pupil",
    "Newbie",
]

export const AtcoderTier = [
    "표시하지않음",
    "Red",
    "Orange",
    "Yellow",
    "Blue",
    "Cyan",
    "Green",
    "Brown",
    "Gray",
]
