export const StacksFolder = "stacks/";
export const StacksFilename: {
    [key: string]: string,
} = {
    "HTML": "html.png",
    "CSS": "css.png",
    "SASS": "sass.png",
    "Javascript": "javascript.png",
    "Rust": "rust.png",
    "Wasm": "wasm.png",
    "jQuery": "jquery.jpeg",
    "React": "react.png",
    "Vue": "vue.png",
    "Angular": "angular.png",
    "Astro": "astro.png",
    "Svelte": "svelte.png",
    "Web Components": "webcomponents.png",
    "Next.js": "nextjs.png",
    "Nuxt.js": "nuxtjs.png",
    "Fresh": "fresh.png",
    "Electron": "electron.jpeg",
    "Storybook": "storybook.png",
    "Rx.js": "rxjs.png",
    "Require.js": "requirejs.png",
    "Firebase": "firebase.jpeg",
    "Google Adsense": "google-adsense.jpeg",
    "Google Analytics": "google-analytics.jpeg",
    "Google Maps": "google-maps.png",
    "Google Tag Manager": "google-tag-manager.png",
    "Bootstrap": "bootstrap.jpeg",
    "Webpack": "webpack.png",
    "Grunt": "grunt.png",
    "Babel": "babel.png",
    "ESlint": "eslint.jpeg",
    "ES6": "es6.jpeg",
    "Node.js": "node.png",
    "Yarn": "yarn.png",
    "Deno": "deno.png",
    "Java": "java.png",
    "Express": "express.png",
    "Flask": "flask.png",
    "Gradle": "gradle.png",
    "GraphQL": "graphql.png",
    "AWS CloudFront": "aws-cloudfront.png",
    "AWS CloudWatch": "aws-cloudwatch.png",
    "AWS EC2": "aws-ec2.png",
    "AWS ELB": "aws-elb.png",
    "AWS Lambda": "aws-lambda.png",
    "AWS RDS": "aws-rds.png",
    "AWS Route53": "aws-route53.png",
    "AWS S3": "aws-s3.png",
    "AWS SES": "aws-ses.png",
    "Azure": "azure.jpeg",
    "Cloud Flare": "cloudflare.png",
    "GCP": "gcp.jpeg",
    "Google Computer Engine": "google-computer-engine.png",
    "CircleCI": "circleci.jpeg",
    "Docker": "docker.png",
    "Docker Compose": "docker-compose.png",
    "Github Pages": "github-pages.png",
    "Heroku": "heroku.png",
    "Android SDK": "android-sdk.png",
    "Android Studio": "android-studio.jpeg",
    "Flutter": "flutter.ong",
    "Ionic": "ionic.jpeg",
    "Centos": "centos.png",
    "Debian": "debian.png",
    "Git": "git.png",
    "Github": "github.jpeg",
    "GitLab": "gitlab.png",
    "Bitbucket": "bitbucket.jpeg",
    "Confluence": "confluence.jpeg",
    "Google Drive": "google-drive.jpeg",
    "C#": "csharp.png",
    "Datadog": "datadog.jpeg",
    "Elastic Search": "elasticsearch.png",
    "Jenkins": "jenkins.png",
    "Jira": "jira.jpeg",
    "Kafka": "kafka.jpeg",
    "Kibana": "kibana.png",
    "Kotlin": "kotlin.png",
    "Kubernetes": "kubernetes.png",
    "Laravel": "laravel.jpeg",
    "Logstash": "logstash.png",
    "Mailgun": "mailgun.png",
    "Maria DB": "mariadb.png",
    "Markdown": "markdown.png",
    "Memcached": "memcached.jpeg",
    "mongodb": "mongodb.png",
    "MySQL": "mysql.png",
    "Nginx": "nginx.png",
    "Node": "node.png",
    "NPM": "npm.png",
    "Objective C": "objective-c.png",
    "OpenSSL": "openssl.png",
    "PHP": "php.jpeg",
    "PostgreSQL": "postgresql.png",
    "Postman": "postman.png",
    "PyCharm": "pycharm.png",
    "Python": "python.png",
    "RabbitMQ": "rabbitmq.jpeg",
    "Rails": "rails.png",
    "React Native": "react-native.jpeg",
    "Redis": "redis.png",
    "Redux": "redux.png",
    "Ruby": "ruby.png",
    "Scala": "scala.png",
    "Selenium": "selenium.jpeg",
    "Sentry": "sentry.png",
    "Shopify": "shopify.png",
    "Slack": "slack.png",
    "SocketIO": "socketio.png",
    "Sourcetree": "sourcetree.png",
    "Spring Boot": "spring-boot.png",
    "SQL Server": "sql-server.png",
    "SQLite": "sqlite.png",
    "Stripe": "stripe.png",
    "Swift": "swift.png",
    "Symfony": "symfony.png",
    "Terraform": "terraform.png",
    "TravisCI": "travisci.png",
    "Trello": "trello.png",
    "Twilio": "twilio.png",
    "Ubuntu": "ubuntu.png",
    "Vagrant": "vagrant.png",
    "Vim": "vim.png",
    "Virtual Box": "virtualbox.png",
    "Visual Studio": "visual-studio.png",
    "VSCode": "vscode.png",
    "WASM": "wasm.png",
    "Wordpress": "wordpress.png",
    "Xcode": "xcode.png",
    "MobX": "mobx.png",
    "React Query": "react-query.png",
    "Jest": "jest.png",
    "Mocha": "mocha.png",
    "Chai": "chai.png",
    "Vercel": "vercel.png",
    "Lodash": "lodash.png",
    "Gulp": "gulp.png",
    "Typescript": "typescript.png",
    "ReScript": "rescript.png",
    "ReasonML": "reasonml.png",
    "Github Actions": "github-actions.png",
    "SWC": "swc.png",
    "Recoil": "recoil.png",
    "Gatsby": "gatsby.png",
    "Gatsby Cloud": "gatsby-cloud.png",
    "Stitches": "stitches.png",
    "Cloudflare Workers": "cloudflare-workers.png",
    "Prismic": "prismic.png",
    "Pnpm": "pnpm.png",
    "ESbuild": "esbuild.png",
    "Remix": "remix.png",
    "Purescript": "purescript.png",
    "Axios": "axios.png",
    "Vite": "vite.png",
    "Solid": "solid.png",
    "Qwik": "qwik.png",
    "Vitest": "vitest.png",
    "Tailwind CSS": "tailwind-css.png",
    "Meterial UI": "meterial-ui.png",
    "Chakra UI": "chakra-ui.png",
    "Web XR": "webxr.png",
    "Three.js": "threejs.png",
};

const Frontend:string[] = [
    "HTML",
    "CSS",
    "SASS",
    "Javascript",
    "Typescript",
    "Rust",
    "Wasm",
    "ReScript",
    "ReasonML",
    "Purescript",
    "jQuery",
    "React",
    "Vue",
    "Angular",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Web Components",
    "Astro",
    "Remix",
    "Fresh",
    "Vite",
    "Qwik",
    "Solid",
    "Electron",
    "MobX",
    "Redux",
    "React Query",
    "Recoil",
    "Storybook",
    "Jest",
    "Mocha",
    "Chai",
    "Vitest",
    "Rx.js",
    "Require.js",
    "Axios",
    "Lodash",
    "Firebase",
    "Google Adsense",
    "Google Analytics",
    "Google Maps",
    "Google Tag Manager",
    "Bootstrap",
    "Tailwind CSS",
    "Meterial UI",
    "Chakra UI",
    "Webpack",
    "Grunt",
    "Gulp",
    "Babel",
    "ESbuild",
    "SWC",
    "ESlint",
    "ES6",
    "Node.js",
    "NPM",
    "Pnpm",
    "Yarn",
    "Deno",
    "AWS CloudFront",
    "AWS Lambda",
    "AWS Route53",
    "AWS S3",
    "Cloud Flare",
    "Cloudflare Workers",
    "CircleCI",
    "Github Pages",
    "Github Actions",
    "Heroku",
    "Vercel",
    "Gatsby",
    "Gatsby Cloud",
    "Stitches",
    "Prismic",
    "Web XR",
    "Three.js"
];
const Backend:string[] = [

];


const DatabaseStacks:string[] = [
];

const MobileStacks:string[] = [
];

const DevOpsStacks:string[] = [
    "AWS CloudFront",
    "AWS CloudWatch",
    "AWS EC2",
    "AWS ELB",
    "AWS Lambda",
    "AWS RDS",
    "AWS Route53",
    "AWS S3",
    "AWS SES",
    "Azure",
    "Cloud Flare",
    "Cloudflare Workers",
    "GCP",
    "Google Computer Engine",
    "CircleCI",
    "Docker",
    "Docker Compose",
    "Github Pages",
    "Github Actions",
    "Heroku",
    "Vercel",
];

const OsStacks:string[] = [
    "Centos",
    "Debian",
]

const CooperationStacks:string[] = [
    "Git",
    "Github",
    "GitLab",
    "Bitbucket",
    "Confluence",
    "Google Drive",
];

const DataStacks:string[] = [
    "Datadog",
    "Elastic Search",
];

const Others:string[] = [
    "C#",
]


const FrontendSets = new Set<string>([
    ...Frontend,
    ...CooperationStacks,
]);
export const FrontendStacks:string[] = [];
FrontendSets.forEach((stack) => {
    FrontendStacks.push(stack);
});
